name: "📚 latest Blog"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *" # Runs every hour, on the hour.

jobs:
  update_blogs:
    name: "Update With Latest Blogs"
    runs-on: ubuntu-latest
    steps:
      - name: "📥  Fetching Repository Contents"
        uses: actions/checkout@main

      - name: "📚  Hashnode Updater"
        uses: "Sachin-chaurasiya/hashnode-blog-action@v0.0.1"
        with:
          HASHNODE_PUBLICATION_NAME: 'blog.sachinchaurasiya.dev'
          POST_COUNT: 6 # MAX Visisble
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
